server 192.168.255.0 255.255.255.0
verb 3
key /etc/openvpn/pki/private/server.key
ca /etc/openvpn/pki/ca.crt
cert /etc/openvpn/pki/issued/server.crt
dh /etc/openvpn/pki/dh.pem

# Security and Routing Settings
proto udp
port 1194
dev tun
keepalive 10 120
persist-key
persist-tun

# Push routes to client for local network access
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"